[package]
name = "ldgerrits/bitzone"
description = "A high-performance, low-footprint, spatial query module"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
	"lib", 
	"lib/**/*.luau",
	"wally.toml",
	"default.project.json",
	"LICENSE.md"
]